spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    ursername: sa
    password:

  jpa:
    show-sql: true

    properties:
      hibernate:
        format_sql: true